apiVersion: v1
kind: ConfigMap
metadata:
  namespace: redis-nginx
  name: nginx-conf
data:
  nginx.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm;
        server_name _;
        location / {
          add_header Content-Type text/plain;
          return 200 'Hello from k8s';
          }
          }
